name: Build via Append and Release to GH & Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build-Append and Release (Docker Hub)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get version
        id: version
        uses: michmich112/extract-version@main
        with:
          # specify here the path to your version file (e.g. package.json, pom.xml...)
          version-file: VERSION
          schema: major.minor.build
      - name: Version Debug
        run: |
          echo "Version to Release -> $VERSION"
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Build CoreDNS
        run: make build-append
    
      - name: Tarball
        run: make tar CUSTOMIZED_VERSION=${{ steps.version.outputs.version }}
      
      - name: Github Release
        run: make github-create-release github-upload github-publish-release CUSTOMIZED_VERSION=${{ steps.version.outputs.version }} GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} GITHUB_REPO=${{ github.repository }}
      
      - name: Docker Build and Push
        run: make docker-build docker-push DOCKER_REPO=nerdynik DOCKER_NAME=coredns-for-homelab
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}